export const TODO = {
  ADD_TODO: "ADD_TODO",
  TOGGLE_TODO: "TOGGLE_TODO",
};

export const EMPLOYEES = {
  GET_EMPLOYEE_REQUEST: "GET_EMPLOYEE_REQUEST", // Loading
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS", // Success
  GET_EMPLOYEE_ERROR: "GET_EMPLOYEE_ERROR", // Error
};
